name: Node.js CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: [$default-branch]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - run: npm ci
            - run: npm test
            - name: Run Build
                run: npm run build
            - name: Publish test coverage report
                uses: EndBug/add-and-commit@v4
                with:
                    add: docs
                    force: true
                    message: Add generated docs
                env:
                    GITHUB_TOKEN: $
